services:
  discord-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-app
    volumes:
      - ./:/usr/src/app

  voicevox-engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox_engine
    ports:
      - "50021:50021"
