services:
  discord-app:
    build:
      context: ./discord-app
      dockerfile: ./Dockerfile
    container_name: discord-app
    volumes:
      - ./discord-app:/usr/src/app

  unittest.db:
    image: postgres:latest
    container_name: postgres-db-unittest
    environment:
      POSTGRES_USER: ${POSTGRES_USER_UNITTEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_UNITTEST}
      POSTGRES_DB: ${POSTGRES_DB_UNITTEST}
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  voicevox-engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox_engine
    ports:
      - "50021:50021"

volumes:
  postgres_test_data:
