name: Bot Run

on:
    pull_request
    # schedule:
      # - cron: '0 5 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - uses: actions/setup-node@v4
            with:
                node-version: "20"
          - run: |
              mkdir -p postgre_sql/backup && touch development_235_backup.sql && wget -O ./postgre_sql/backup/development_235_backup.sql "${{ secrets.POSTGRES_DB_BACKUP_URL }}" && npm install --save-dev @types/node && docker compose up -d && docker logs discord-app -f
            env:
                USER_ID_FOR_MAKI: ${{ secrets.USER_ID_FOR_MAKI }}
                POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                POSTGRES_DB_BACKUP_URL: ${{ secrets.POSTGRES_DB_BACKUP_URL }}
                POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                POSTGRES_USER_UNITTEST: ${{ secrets.POSTGRES_USER_UNITTEST }}
                POSTGRES_PASSWORD_UNITTEST: ${{ secrets.POSTGRES_PASSWORD_UNITTEST }}
                POSTGRES_DB_UNITTEST: ${{ secrets.POSTGRES_DB_UNITTEST }}
