name: Bot Run

on:
    pull_request
    # schedule:
      # - cron: '0 5 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - uses: actions/setup-node@v4
            with:
                node-version: "20"
          - run: |
              cd discord-app && 
              echo "${{ secrets.ENV_VALUES }}" > .env && 
              cd .. && 
              mkdir -p postgre_sql/backup && 
              touch ./postgre_sql/backup/development_235_backup.sql && 
              wget "${{ secrets.POSTGRES_DB_BACKUP_URL }}" -O ./postgre_sql/backup/development_235_backup.sql && 
              cd discord-app && 
              npm install && 
              cd .. && 
              docker compose up -d && 
              docker exec postgres-db cat ./docker-entrypoint-initdb.d/development_235_backup.sql && 
              docker logs discord-app -f
            env:
              POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
              POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
              POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
              POSTGRES_DB_UNITTEST: ${{ secrets.POSTGRES_DB_UNITTEST }}
              POSTGRES_PASSWORD_UNITTEST: ${{ secrets.POSTGRES_PASSWORD_UNITTEST }}
              POSTGRES_USER_UNITTEST: ${{ secrets.POSTGRES_USER_UNITTEST }}
