name: Bot Run

on:
    schedule:
      - cron: '0 23 * * *' # 8時
      - cron: '0 5 * * *'  # 14時
      - cron: '0 11 * * *' # 20時
      - cron: '0 17 * * *' # 2時

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - uses: actions/setup-node@v4
            with:
                node-version: "20"
          - run: |
              cd discord-app && 
              echo "${{ secrets.ENV_VALUES }}" > .env && 
              npm install && 
              npm install sequelize-cli && 
              cd .. && 
              docker compose up -d && 
              cd discord-app && 
              npx tsc -p . && 
              npx sequelize-cli db:migrate --env development && 
              cd .. && 
              docker logs discord-app -f
