name: JavaScript Linter Check

on: pull_request

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: ESLint Linter Check
              uses: reviewdog/action-eslint@v1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                fail_on_error: true
