name: Jest Check

on:
    pull_request

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                test-script: npm run test:coverage
