name: UnitTest Check

on:
    push

jobs:
    jest:
        runs-on: ubuntu-latest
        steps:
              - uses: actions/checkout@master
              - uses: actions/setup-node@v4
                with:
                    node-version: "20"
              - run: |
                  docker compose up unittest.db -d && cd discord-app && npm install && npm run test && cd .. && docker compose rm -fsv unittest.db
