name: UnitTest Check

on:
    push

jobs:
    jest:
        runs-on: ubuntu-latest
        steps:
              - uses: actions/checkout@master
              - uses: actions/setup-node@v4
                with:
                    node-version: "20"
              - run: cd discord-app
              - run: npm install
              - run: npm run test
